version: 2
updates:
  - package-ecosystem: "npm"
    directory: "workbench"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    groups:
      action-updates:
        patterns:
          - "*" # Groups ALL GitHub Actions updates together

