import logging
import time

import altair
import geopandas
import geometamaker
import pandas

from natcap.invest import __version__
from natcap.invest import gettext, get_locale
from natcap.invest.reports import jinja_env, raster_utils, report_constants, \
    vector_utils
from natcap.invest.spec import ModelSpec

from natcap.invest.reports.raster_utils import RasterDatatype, \
    RasterPlotConfig, RasterTransform, SpecialValueConfig

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/urban_mental_health.html')

MAP_WIDTH = 450  # pixels

NEAR_ZERO_RANGE = (-0.01, 0.01)


def infer_continuous_or_divergent(raster_path: str) -> str:
    """Infer if raster should have a 'continuous' or 'divergent' color ramp.

    Rules:
        - If min value < ~0 and max value > ~0--> 'divergent'
        - Else --> 'continuous'

    Args:
        raster_path (str): Path to raster.

    Returns:
        str: 'continuous' or 'divergent'
    """
    # read raster's geometamaker metadata to get min value
    resource = geometamaker.describe(raster_path)
    min_val = float(
        resource.data_model.bands[0].gdal_metadata['STATISTICS_MINIMUM'])
    max_val = float(
        resource.data_model.bands[0].gdal_metadata['STATISTICS_MAXIMUM'])

    if min_val < NEAR_ZERO_RANGE[0] and max_val > NEAR_ZERO_RANGE[1]:
        return RasterDatatype.divergent
    else:
        return RasterDatatype.continuous


def _generate_agg_results_table(preventable_cases_cost_sum_table_path: str,
                                cost: float | None) -> str:
    full_table_df = pandas.read_csv(preventable_cases_cost_sum_table_path)
    total_cases = list(full_table_df['total_cases'])[-1]
    table_df = pandas.DataFrame({'Total Preventable Cases': [total_cases]})
    if cost:
        total_cost = list(full_table_df['total_cost'])[-1]
        table_df['Total Preventable Cost'] = [total_cost]

    return table_df.to_html(index=False)


def _create_aggregate_map(
        geodataframe,
        xy_ratio,
        attribute,
        title):
    """Create a choropleth map for a given attribute and return Vega JSON."""

    # if the attribute has any negative values, use a divergent color
    # scale; otherwise, use a continuous color scale
    if (geodataframe[attribute] < 0).any():
        scale = altair.Scale(scheme='purpleorange', reverse=True, domainMid=0)
    else:
        scale = altair.Scale(scheme='purples')

    chart = altair.Chart(geodataframe).mark_geoshape(
        stroke="white",
        strokeWidth=0.5
    ).project(
        type='identity',
        reflectY=True
    ).encode(
        color=altair.Color(
            f'{attribute}:Q',
            scale=scale,
            legend=altair.Legend(title=attribute)
        ),
        tooltip=[
            altair.Tooltip(f'{attribute}:Q', title=attribute, format=',.2f')
        ]
    ).properties(
        width=MAP_WIDTH,
        height=MAP_WIDTH / xy_ratio,
        title=title
    ).configure_legend(**vector_utils.LEGEND_CONFIG)

    return chart.to_json()


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """
    ndvi_colorramp = 'viridis_r'

    input_raster_config_list = []
    if args_dict['lulc_base']:
        input_raster_config_list.append(
            RasterPlotConfig(
                raster_path=args_dict['lulc_base'],
                datatype=RasterDatatype.nominal,
                spec=model_spec.get_input('lulc_base')
            )
        )

    if args_dict['lulc_alt']:
        input_raster_config_list.append(
            RasterPlotConfig(
                raster_path=args_dict['lulc_alt'],
                datatype=RasterDatatype.nominal,
                spec=model_spec.get_input('lulc_alt')
            )
        )

    if args_dict["model_option"] == 'ndvi':
        input_raster_config_list.insert(0,
            RasterPlotConfig(
                raster_path=args_dict['ndvi_base'],
                datatype=RasterDatatype.continuous,
                spec=model_spec.get_input('ndvi_base'),
                colormap=ndvi_colorramp
            )
        )
        input_raster_config_list.insert(1,
            RasterPlotConfig(
                raster_path=args_dict['ndvi_alt'],
                datatype=RasterDatatype.continuous,
                spec=model_spec.get_input('ndvi_alt'),
                colormap=ndvi_colorramp
            )
        )
    else:
        intermediate_reclass_lulc_list = [
            RasterPlotConfig(
                raster_path=file_registry['ndvi_base_aligned_masked'],
                datatype=RasterDatatype.continuous,
                spec=model_spec.get_output('ndvi_base_aligned_masked'),
                colormap=ndvi_colorramp
            ),
            # reclassified baseline lulc to ndvi values based on means
            RasterPlotConfig(
                raster_path=file_registry['ndvi_alt_aligned_masked'],
                datatype=RasterDatatype.continuous,
                spec=model_spec.get_output('ndvi_alt_aligned_masked'),
                colormap=ndvi_colorramp
            )
        ]
    input_raster_config_list.append(
        RasterPlotConfig(
            raster_path=args_dict['population_raster'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_input('population_raster')
        )
    )

    intermediate_baseline_list = [
        RasterPlotConfig(
            raster_path=file_registry['baseline_prevalence_raster'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('baseline_prevalence_raster')
        ),
        RasterPlotConfig(
            raster_path=file_registry['baseline_cases'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('baseline_cases')
        )]

    intermediate_delta_ndvi_list = [
        RasterPlotConfig(
            raster_path=file_registry['ndvi_base_buffer_mean_clipped'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('ndvi_base_buffer_mean_clipped'),
            colormap=ndvi_colorramp
        ),
        RasterPlotConfig(
            raster_path=file_registry['ndvi_alt_buffer_mean_clipped'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('ndvi_alt_buffer_mean_clipped'),
            colormap=ndvi_colorramp
        ),
        RasterPlotConfig(
            raster_path=file_registry['delta_ndvi'],
            datatype=RasterDatatype.divergent,
            spec=model_spec.get_output('delta_ndvi'),
        )]

    datatype = infer_continuous_or_divergent(file_registry['preventable_cases'])
    is_continuous = datatype == RasterDatatype.continuous
    common_kwargs = {
        "datatype": datatype,
        "transform": RasterTransform.linear if is_continuous else RasterTransform.log,
    }
    if is_continuous:
        common_kwargs["special_values"] = SpecialValueConfig(
            extend="min",
            threshold=NEAR_ZERO_RANGE[1],
            label=str(NEAR_ZERO_RANGE[0]),
            color='#FEE0B6'  # light orange
        )
        common_kwargs["colormap"] = 'Purples'

    output_raster_config_list = [
        RasterPlotConfig(
            raster_path=file_registry['preventable_cases'],
            spec=model_spec.get_output('preventable_cases'),
            **common_kwargs
        )
        ]
    if args_dict['health_cost_rate']:
        output_raster_config_list.append(
            RasterPlotConfig(
                raster_path=file_registry['preventable_cost'],
                spec=model_spec.get_output('preventable_cost'),
                **common_kwargs
            )
        )

    inputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        input_raster_config_list)
    input_raster_caption = raster_utils.caption_raster_list(
        input_raster_config_list)

    outputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        output_raster_config_list)
    output_raster_caption = raster_utils.caption_raster_list(
        output_raster_config_list)

    intermediate_baseline_img_src = raster_utils.plot_and_base64_encode_rasters(
        intermediate_baseline_list)
    intermediate_baseline_img_caption = raster_utils.caption_raster_list(
        intermediate_baseline_list)

    intermediate_delta_ndvi_img_src = raster_utils.plot_and_base64_encode_rasters(
        intermediate_delta_ndvi_list)
    intermediate_delta_ndvi_img_caption = raster_utils.caption_raster_list(
        intermediate_delta_ndvi_list)

    if args_dict["model_option"] == 'lulc':
        intermediate_reclass_lulc_img_src = raster_utils.plot_and_base64_encode_rasters(
            intermediate_reclass_lulc_list)
        intermediate_reclass_lulc_img_caption = raster_utils.caption_raster_list(
            intermediate_reclass_lulc_list)
    else:
        intermediate_reclass_lulc_img_src = None
        intermediate_reclass_lulc_img_caption = None

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict, model_spec).to_html(na_rep='')

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    agg_results_table = _generate_agg_results_table(
        file_registry['preventable_cases_cost_sum_table'],
        args_dict.get('health_cost_rate'))

    # Vector maps
    aggregate_vector_path = file_registry['preventable_cases_cost_sum_vector']
    aggregate_gdf = geopandas.read_file(aggregate_vector_path)
    _, xy_ratio = vector_utils.get_geojson_bbox(aggregate_gdf)

    cases_map_json = _create_aggregate_map(
        aggregate_gdf,
        xy_ratio,
        'sum_cases',
        gettext('Preventable Cases by AOI Feature')
    )
    cases_map_caption = [
        model_spec.get_output('preventable_cases_cost_sum_vector')
        .get_field('sum_cases').about
    ]

    cost_map_json = None
    cost_map_caption = None

    if 'sum_cost' in aggregate_gdf.columns:
        nonnull_cost = aggregate_gdf['sum_cost'].notna().any()
        nonzero_cost = (aggregate_gdf['sum_cost'].fillna(0) != 0).any()
        if nonnull_cost and nonzero_cost:
            cost_map_json = _create_aggregate_map(
                aggregate_gdf,
                xy_ratio,
                'sum_cost',
                gettext('Preventable Cost by AOI Feature')
            )
            cost_map_caption = [
                model_spec.get_output('preventable_cases_cost_sum_vector')
                .get_field('sum_cost').about
            ]

    aggregate_map_source_list = [
        model_spec.get_output('preventable_cases_cost_sum_vector').path
    ]

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            locale=get_locale(),
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            agg_results_table=agg_results_table,
            inputs_img_src=inputs_img_src,
            inputs_caption=input_raster_caption,
            outputs_img_src=outputs_img_src,
            outputs_caption=output_raster_caption,
            intermediate_baseline_img_src=intermediate_baseline_img_src,
            intermediate_baseline_img_caption=intermediate_baseline_img_caption,
            intermediate_delta_ndvi_img_src=intermediate_delta_ndvi_img_src,
            intermediate_delta_ndvi_img_caption=intermediate_delta_ndvi_img_caption,
            intermediate_reclass_lulc_img_src=intermediate_reclass_lulc_img_src,
            intermediate_reclass_lulc_img_caption=intermediate_reclass_lulc_img_caption,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            lulc_pre_caption=report_constants.LULC_PRE_CAPTION,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            cases_map_json=cases_map_json,
            cost_map_json=cost_map_json,
            cases_map_caption=cases_map_caption,
            cost_map_caption=cost_map_caption,
            aggregate_map_source_list=aggregate_map_source_list,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
