# Shared report generator for SDR and NDR
# (to be extended to support other similar models, and renamed as appropriate)

import logging
import time

from natcap.invest import __version__
from natcap.invest import gettext
from natcap.invest.reports import (
    jinja_env, report_constants, sdr_ndr_utils, raster_utils)


LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/sdr-ndr-report.html')


def report(file_registry, args_dict, model_spec, target_html_filepath,
           raster_plot_configs: raster_utils.RasterPlotConfigGroup,
           raster_plot_captions: raster_utils.RasterPlotCaptionGroup,
           results_vector_id, results_vector_cols_to_sum):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): the ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): the arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.
        raster_plot_configs (``raster_utils.RasterPlotConfigGroup``): group of
            ``RasterPlotConfig`` to be used to plot input, output, and
            intermediate output rasters.
        raster_plot_captions (``raster_utils.RasterPlotCaptionGroup``):
            captions to accompany input, output, and intermediate plots.
        results_vector_id (str): id of the results vector generated by the
            model (e.g., for NDR, ``watershed_results_ndr``),
        results_vector_cols_to_sum (list[str]): list of column names in the
            results vector to include when calculating totals.

    Returns:
        ``None``
    """

    inputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        raster_plot_configs.inputs)

    outputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        raster_plot_configs.outputs)

    intermediate_img_src = raster_utils.plot_and_base64_encode_rasters(
        raster_plot_configs.intermediates)

    (ws_vector_table, ws_vector_totals_table) = (
        sdr_ndr_utils.generate_results_table_from_vector(
            file_registry[results_vector_id], results_vector_cols_to_sum))

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict).to_html(na_rep='')

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filename=f'{model_spec.model_id}_report{args_dict["results_suffix"]}.html',
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            inputs_img_src=inputs_img_src,
            inputs_caption=raster_plot_captions.inputs,
            outputs_img_src=outputs_img_src,
            outputs_caption=raster_plot_captions.outputs,
            intermediate_outputs_heading=gettext('Stream Network Maps'),
            intermediate_outputs_img_src=intermediate_img_src,
            intermediate_outputs_caption=raster_plot_captions.intermediates,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            ws_vector_table=ws_vector_table,
            ws_vector_totals_table=ws_vector_totals_table,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
