import logging
import os
import time

import altair
import geopandas
import pandas

from natcap.invest import __version__
from natcap.invest import gettext
import natcap.invest.spec
from natcap.invest.reports import jinja_env, raster_utils, report_constants, vector_utils
from natcap.invest.unit_registry import u


LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/seasonal_water_yield.html')

MAP_WIDTH = 450 # pixels

OUTPUT_RASTER_PLOT_TUPLES = [
    ('l_aligned', 'continuous'),
    ('l_avail', 'continuous'),
    ('b', 'continuous'),
    ('b_sum', 'continuous'),
    ('qf', 'continuous')
]


def _create_aggregate_map(geodataframe, extent_feature, xy_ratio, attribute,
                          title):
    attr_map = altair.Chart(geodataframe).mark_geoshape(
        clip=True,
        stroke="white",
        strokeWidth=0.5
    ).project(
        type='identity',
        reflectY=True,
        fit=extent_feature
    ).encode(
        color=attribute,
        tooltip=[altair.Tooltip(attribute, title=attribute)]
    ).properties(
        width=MAP_WIDTH,
        height=MAP_WIDTH / xy_ratio,
        title=title
    ).configure_legend(**vector_utils.LEGEND_CONFIG)

    return attr_map.to_json()
#    qb_map = altair.Chart(aggregated_results).mark_geoshape(
#        clip=True,
#        stroke="white",
#        strokeWidth=0.5
#    ).project(
#        type='identity',
#        reflectY=True,
#        fit=extent_feature
#    ).encode(
#        color='qb',
#        tooltip=[altair.Tooltip("qb", title="qb")]
#    ).properties(
#        width=MAP_WIDTH,
#        height=MAP_WIDTH / xy_ratio,
#        title='Mean local recharge value within the watershed'
#    ).configure_legend(**vector_utils.LEGEND_CONFIG)
#    qb_map_caption = [model_spec.get_output(
#        'aggregate_vector').get_field('qb').about]


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an html summary of Coastal Vulnerability results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by ``natcap.invest.seasonal_water_yield.execute``.
        args_dict (dict): The arguments that were passed to
            ``natcap.invest.seasonal_water_yield.execute``.
        model_spec (natcap.invest.spec.ModelSpec):
            ``natcap.invest.seasonal_water_yield.MODEL_SPEC``
        target_html_filepath (str): path to an html file generated by this
            function.

    Returns:
        None
    """

    aggregated_results = geopandas.read_file(file_registry['aggregate_vector'])
    extent_feature, xy_ratio = vector_utils.get_geojson_bbox(aggregated_results)

    qb_map_json = _create_aggregate_map(
        aggregated_results, extent_feature, xy_ratio, 'qb',
        gettext('Mean local recharge value within the watershed'))
    qb_map_caption = [
        model_spec.get_output('aggregate_vector').get_field('qb').about,
        gettext('Values are in millimeters, but should be interpreted as '
                'relative values, not absolute values.')]

    vri_sum_map_json = _create_aggregate_map(
        aggregated_results, extent_feature, xy_ratio, 'vri_sum',
        gettext('Total recharge contribution of the watershed'))
    vri_sum_map_caption = [
        model_spec.get_output('aggregate_vector').get_field('vri_sum').about,
        gettext('The sum of ``Vri_[suffix].tif`` pixel values within the watershed.')]

    vector_map_source_list = [model_spec.get_output('aggregate_vector').path]

    output_raster_plot_configs = raster_utils.build_raster_plot_configs(
            file_registry, OUTPUT_RASTER_PLOT_TUPLES)
    outputs_img_src = raster_utils.plot_and_base64_encode_rasters(
            output_raster_plot_configs)
    output_raster_caption = raster_utils.generate_caption_from_raster_list(
            [(id, 'output') for (id, _) in OUTPUT_RASTER_PLOT_TUPLES],
            args_dict, file_registry, model_spec)

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            outputs_img_src=outputs_img_src,
            outputs_caption=output_raster_caption,
            qb_map_json=qb_map_json,
            qb_map_caption=qb_map_caption,
            vri_sum_map_json=vri_sum_map_json,
            vri_sum_map_caption=vri_sum_map_caption,
            aggregate_map_source_list=vector_map_source_list,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
