from natcap.invest.reports import raster_utils
from natcap.invest.reports import sdr_ndr_utils
from natcap.invest.reports import sdr_ndr_report_generator

CALC_N = 'calc_n'
CALC_P = 'calc_p'

INPUT_RASTER_PLOT_TUPLES = [
    ('dem_path', 'continuous'),
    ('runoff_proxy_path', 'continuous'),
    ('lulc_path', 'nominal')
]

OUTPUT_RASTER_PLOT_TUPLES = {
    CALC_N: [
        ('n_surface_export', 'continuous', 'linear'),
        ('n_subsurface_export', 'continuous', 'linear'),
        ('n_total_export', 'continuous', 'linear'),
    ],
    CALC_P: [
        ('p_surface_export', 'continuous', 'linear')
    ],
}

INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES = [
    ('masked_dem', 'continuous'),
    ('what_drains_to_stream', 'binary'),
    ('stream', 'binary_high_contrast'),
]

RESULTS_VECTOR_COL_NAMES = {
    CALC_N: [
        'n_surface_load',
        'n_surface_export',
        'n_subsurface_export',
        'n_total_export',
        'n_subsurface_load',
    ],
    CALC_P: [
        'p_surface_load',
        'p_surface_export',
    ]
}


def _get_nutrient_dependent_list(args_dict, reference_dict):
    """Build a list of items based on which nutrients were calculated.

    Args:
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        reference_dict (dict[str, list[any]): The reference dict to copy items
            from. Must contain keys ``CALC_N`` and ``CALC_P``.

    Returns:
        A list of the items found in ``reference_dict[CALC_N]``,
            ``reference_dict[CALC_P]``, or both, depending on the values in
            ``args_dict``.
    """
    item_list = []
    for key in [CALC_N, CALC_P]:
        if args_dict[key]:
            item_list.extend(reference_dict[key])
    return item_list


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    output_raster_plot_tuples = _get_nutrient_dependent_list(
        args_dict, OUTPUT_RASTER_PLOT_TUPLES)

    input_raster_plot_configs = raster_utils.build_raster_plot_configs(
        args_dict, INPUT_RASTER_PLOT_TUPLES)

    output_raster_plot_configs = raster_utils.build_raster_plot_configs(
            file_registry, output_raster_plot_tuples)

    intermediate_raster_plot_configs = raster_utils.build_raster_plot_configs(
            file_registry, INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES)

    raster_plot_configs = raster_utils.RasterPlotConfigGroup(
        input_raster_plot_configs,
        output_raster_plot_configs,
        intermediate_raster_plot_configs)

    input_raster_caption = raster_utils.generate_caption_from_raster_list(
        [(id, 'input') for (id, _) in INPUT_RASTER_PLOT_TUPLES],
        args_dict, file_registry, model_spec)
    output_raster_caption = raster_utils.generate_caption_from_raster_list(
        [(id, 'output') for (id, _, _) in output_raster_plot_tuples],
        args_dict, file_registry, model_spec)
    intermediate_raster_caption = raster_utils.generate_caption_from_raster_list(
        [(id, 'output') for (id, _) in INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES],
        args_dict, file_registry, model_spec)
    intermediate_raster_caption = (
        sdr_ndr_utils.update_caption_with_stream_map_info(
            intermediate_raster_caption, args_dict['flow_dir_algorithm']))

    captions = raster_utils.RasterPlotCaptionGroup(
        inputs=input_raster_caption,
        outputs=output_raster_caption,
        intermediates=intermediate_raster_caption)

    results_vector_id = 'watershed_results_ndr'
    results_vector_cols_to_sum = _get_nutrient_dependent_list(
        args_dict, RESULTS_VECTOR_COL_NAMES)

    sdr_ndr_report_generator.report(
        file_registry, args_dict, model_spec, target_html_filepath,
        raster_plot_configs, captions,
        results_vector_id, results_vector_cols_to_sum)
