from natcap.invest import gettext
from natcap.invest.reports import raster_utils
from natcap.invest.reports import sdr_ndr_report_generator

CALC_N = 'calc_n'
CALC_P = 'calc_p'

RESULTS_VECTOR_COL_NAMES = {
    CALC_N: [
        'n_surface_load',
        'n_surface_export',
        'n_subsurface_export',
        'n_total_export',
        'n_subsurface_load',
    ],
    CALC_P: [
        'p_surface_load',
        'p_surface_export',
    ]
}


def _get_nutrient_dependent_list(args_dict, reference_dict):
    """Build a list of items based on which nutrients were calculated.

    Args:
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        reference_dict (dict[str, list[any]): The reference dict to copy items
            from. Must contain keys ``CALC_N`` and ``CALC_P``.

    Returns:
        A list of the items found in ``reference_dict[CALC_N]``,
            ``reference_dict[CALC_P]``, or both, depending on the values in
            ``args_dict``.
    """
    item_list = []
    for key in [CALC_N, CALC_P]:
        if args_dict[key]:
            item_list.extend(reference_dict[key])
    return item_list


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    dem_config = raster_utils.RasterPlotConfig(
        raster_path=args_dict['dem_path'],
        datatype='continuous',
        spec=model_spec.get_input('dem_path'))
    runoff_proxy_config = raster_utils.RasterPlotConfig(
        raster_path=args_dict['runoff_proxy_path'],
        datatype='continuous',
        spec=model_spec.get_input('runoff_proxy_path'))
    lulc_config = raster_utils.RasterPlotConfig(
        raster_path=args_dict['lulc_path'],
        datatype='nominal',
        spec=model_spec.get_input('lulc_path'))
    input_raster_plot_configs = [dem_config, runoff_proxy_config, lulc_config]

    n_surface_export_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['n_surface_export'],
        datatype='continuous',
        spec=model_spec.get_output('n_surface_export'))
    n_subsurface_export_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['n_subsurface_export'],
        datatype='continuous',
        spec=model_spec.get_output('n_subsurface_export'))
    n_total_export_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['n_total_export'],
        datatype='continuous',
        spec=model_spec.get_output('n_total_export'))
    p_surface_export_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['p_surface_export'],
        datatype='continuous',
        spec=model_spec.get_output('p_surface_export'))

    output_raster_plot_configs = []
    if CALC_N in args_dict:
        output_raster_plot_configs.extend(
            [n_surface_export_config,
             n_subsurface_export_config,
             n_total_export_config])
    if CALC_P in args_dict:
        output_raster_plot_configs.extend([p_surface_export_config])

    masked_dem_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['masked_dem'],
        datatype='continuous',
        spec=model_spec.get_output('masked_dem'))
    what_drains_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['what_drains_to_stream'],
        datatype='binary',
        spec=model_spec.get_output('what_drains_to_stream'))
    stream_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['stream'],
        datatype='binary_high_contrast',
        spec=model_spec.get_output('stream'),
        subtitle=f'flow algorithm: {args_dict["flow_dir_algorithm"]}')
    stream_config.caption += gettext(
        'Results were generated using the following flow direction '
        'algorithm:')
    stream_config.caption += gettext(
        'The stream network may look incomplete at  this resolution, and '
        'therefore it may be necessary to view the  full-resolution raster '
        'in GIS to assess its accuracy.')
    intermediate_raster_plot_configs = [
        masked_dem_config, what_drains_config, stream_config]

    raster_plot_configs = raster_utils.RasterPlotConfigGroup(
        input_raster_plot_configs,
        output_raster_plot_configs,
        intermediate_raster_plot_configs)

    results_vector_id = 'watershed_results_ndr'
    results_vector_cols_to_sum = _get_nutrient_dependent_list(
        args_dict, RESULTS_VECTOR_COL_NAMES)

    sdr_ndr_report_generator.report(
        file_registry, args_dict, model_spec, target_html_filepath,
        raster_plot_configs,
        results_vector_id, results_vector_cols_to_sum)
