import csv
import logging
import os
import time

import altair
import geopandas
import pandas

from natcap.invest import __version__
from natcap.invest import gettext
import natcap.invest.spec
from natcap.invest.reports import jinja_env
from natcap.invest.reports import raster_utils
from natcap.invest.reports import report_constants
from natcap.invest.reports import sdr_ndr_utils
from natcap.invest.reports import vector_utils
from natcap.invest.reports.raster_utils import RasterDatatype
from natcap.invest.reports.raster_utils import RasterPlotConfig
from natcap.invest.unit_registry import u


LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/annual_water_yield.html')


def _caption_fields_in_table(model_spec, spec_output_id, table_df):
    output_fields = {field.id: field.about for field in model_spec.get_output(
        spec_output_id).columns}

    for field in output_fields.keys():
        try:
            units = model_spec.get_output(spec_output_id).get_column(field).units
            output_fields[field] += gettext(" (Units: {units})").format(units=units)
        except AttributeError:
            pass
    col_names = table_df.columns.to_list()

    table_caption = [
        f"{field}: {about}" for field, about in output_fields.items()
        if field in col_names]

    return table_caption


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an html summary of Annual Water Yield results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by ``natcap.invest.annual_water_yield.execute``.
        args_dict (dict): The arguments that were passed to
            ``natcap.invest.annual_water_yield.execute``.
        model_spec (natcap.invest.spec.ModelSpec):
            ``natcap.invest.annual_water_yield.MODEL_SPEC``
        target_html_filepath (str): path to an html file generated by this
            function.

    Returns:
        None
    """

    # water yield, precip, and aet rasters
    wyield_config = RasterPlotConfig(
            raster_path=file_registry['wyield'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('wyield'))
    precip_aet_config_list = [
        RasterPlotConfig(
            raster_path=file_registry['precip'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('precip')),
        RasterPlotConfig(
            raster_path=file_registry['aet'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('aet'))
    ]
    wyield_img_src = raster_utils.plot_and_base64_encode_rasters(
        [wyield_config])
    precip_aet_img_src = raster_utils.plot_and_base64_encode_rasters(
        precip_aet_config_list)
    wyield_raster_caption = raster_utils.caption_raster_list(
        [wyield_config] + precip_aet_config_list)

    # watershed aggregate table
    w_aggregate_df = pandas.read_csv(file_registry['watershed_results_wyield_csv'])
    w_aggregate_table_caption = _caption_fields_in_table(
        model_spec, 'watershed_results_wyield_csv', w_aggregate_df)

    watershed_results_table = w_aggregate_df.to_html(index=False,
        classes=['datatable', 'paginate'])

    watershed_map_params = None
    (num_rows, _) = w_aggregate_df.shape
    if num_rows > 1:
        w_results = geopandas.read_file(file_registry['watershed_results_wyield'])
        _, xy_ratio = vector_utils.get_geojson_bbox(w_results)

        w_wyield_vol_json = vector_utils.create_aggregate_map(
            w_results, xy_ratio, 'wyield_vol', 'blues',
            gettext("Total volume of water yield ({units})").format(
                units=model_spec.get_output(
                    'watershed_results_wyield').get_field('wyield_vol').units))
        w_wyield_vol_caption = [
            model_spec.get_output('watershed_results_wyield').get_field('wyield_vol').about]
        w_map_source_list = [model_spec.get_output('watershed_results_wyield').path]

        watershed_map_params = {
            "json": w_wyield_vol_json,
            "caption": w_wyield_vol_caption,
            "sources": w_map_source_list
        }

    valuation_results = None
    if num_rows > 1 and args_dict['valuation_table_path']:
        hp_energy_json = vector_utils.create_aggregate_map(
            w_results, xy_ratio, 'hp_energy', 'blues',
            gettext("In Energy Production Terms ({units})").format(
                units=model_spec.get_output(
                    'watershed_results_wyield').get_field('hp_energy').units))
        hp_energy_caption = [
            model_spec.get_output('watershed_results_wyield').get_field('hp_energy').about]

        hp_val_json = vector_utils.create_aggregate_map(
            w_results, xy_ratio, 'hp_val', 'blues',
            gettext("In Economic Terms ({units})").format(
                units=model_spec.get_output(
                    'watershed_results_wyield').get_field('hp_val').units))
        hp_val_caption = [
            model_spec.get_output('watershed_results_wyield').get_field('hp_val').about]

        source_list = [model_spec.get_output('watershed_results_wyield').path]

        valuation_title = gettext("Hydropower Production by Watershed")
        valuation_results = {
            "energy_json": hp_energy_json,
            "energy_caption": hp_energy_caption,
            "val_json": hp_val_json,
            "val_caption": hp_val_caption,
            "source_list": source_list,
            "title": valuation_title
        }

    subwatershed_results = None
    if args_dict['sub_watersheds_path']:
        sw_results = geopandas.read_file(file_registry['subwatershed_results_wyield'])
        _, xy_ratio = vector_utils.get_geojson_bbox(sw_results)

        sw_wyield_vol_json = vector_utils.create_aggregate_map(
            sw_results, xy_ratio, 'wyield_vol', 'blues',
            gettext("Total volume of water yield ({units})").format(
                units=model_spec.get_output(
                    'subwatershed_results_wyield').get_field('wyield_vol').units))
        sw_wyield_vol_caption = [
            model_spec.get_output('subwatershed_results_wyield').get_field('wyield_vol').about]
        sw_map_source_list = [model_spec.get_output('subwatershed_results_wyield').path]

        # subwatershed aggregate table
        sw_aggregate_df = pandas.read_csv(file_registry['subwatershed_results_wyield_csv'])
        sw_aggregate_table_caption = _caption_fields_in_table(
            model_spec, 'subwatershed_results_wyield_csv', sw_aggregate_df)
        sw_aggregate_table_source_list = [
            model_spec.get_output('subwatershed_results_wyield_csv').path]

        subwatershed_results = {
            "map_json": sw_wyield_vol_json,
            "map_caption": sw_wyield_vol_caption,
            "map_sources": sw_map_source_list,
            "table": sw_aggregate_df.to_html(index=False,
                                             classes=['datatable', 'paginate']),
            "table_caption": sw_aggregate_table_caption,
        }

    input_raster_config_list = [
        RasterPlotConfig(
            raster_path=args_dict['lulc_path'],
            datatype=RasterDatatype.nominal,
            spec=model_spec.get_input('lulc_path')),
        RasterPlotConfig(
            raster_path=args_dict['precipitation_path'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_input('precipitation_path')),
        RasterPlotConfig(
            raster_path=args_dict['eto_path'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_input('eto_path')),
        RasterPlotConfig(
            raster_path=args_dict['pawc_path'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_input('pawc_path')),
        RasterPlotConfig(
            raster_path=args_dict['depth_to_root_rest_layer_path'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_input('depth_to_root_rest_layer_path'))
    ]
    inputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        input_raster_config_list)
    inputs_raster_caption = raster_utils.caption_raster_list(
        input_raster_config_list)

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict, model_spec).to_html(na_rep='')

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            wyield_img_src=wyield_img_src,
            precip_aet_img_src=precip_aet_img_src,
            wyield_raster_caption=wyield_raster_caption,
            watershed_table=watershed_results_table,
            watershed_table_caption=w_aggregate_table_caption,
            watershed_map_params=watershed_map_params,
            valuation_results=valuation_results,
            subwatershed_results=subwatershed_results,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            inputs_img_src=inputs_img_src,
            inputs_caption=inputs_raster_caption,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
