export const ipcMainChannels = {
  ADD_PLUGIN: 'add-plugin',
  CHANGE_LANGUAGE: 'change-language',
  CHECK_FILE_PERMISSIONS: 'check-file-permissions',
  CHECK_STORAGE_TOKEN: 'check-storage-token',
  DOWNLOAD_URL: 'download-url',
  GET_ELECTRON_PATHS: 'get-electron-paths',
  GET_N_CPUS: 'get-n-cpus',
  GET_SETTING: 'get-setting',
  GET_LANGUAGE: 'get-language',
  INVEST_KILL: 'invest-kill',
  INVEST_READ_LOG: 'invest-read-log',
  INVEST_RUN: 'invest-run',
  INVEST_VERSION: 'invest-version',
  IS_FIRST_RUN: 'is-first-run',
  LAUNCH_PLUGIN_SERVER: 'launch-plugin-server',
  LOGGER: 'logger',
  OPEN_EXTERNAL_URL: 'open-external-url',
  OPEN_LOCAL_HTML: 'open-local-html',
  SET_SETTING: 'set-setting',
  SHOW_ITEM_IN_FOLDER: 'show-item-in-folder',
  SHOW_OPEN_DIALOG: 'show-open-dialog',
  SHOW_SAVE_DIALOG: 'show-save-dialog',
};
