export const ipcMainChannels = {
  SHOW_OPEN_DIALOG: 'show-open-dialog',
  SHOW_SAVE_DIALOG: 'show-save-dialog',
  SHOW_ITEM_IN_FOLDER: 'show-item-in-folder',
  DOWNLOAD_URL: 'download-url',
  INVEST_RUN: 'invest-run',
  INVEST_KILL: 'invest-kill',
  INVEST_READ_LOG: 'invest-read-log',
  IS_FIRST_RUN: 'is-first-run',
  SET_LANGUAGE: 'set-language',
  GETTEXT: 'gettext',
  GET_N_CPUS: 'get-n-cpus',
  CHECK_STORAGE_TOKEN: 'check-storage-token',
  IS_DEV_MODE: 'is-dev-mode',
};
