from natcap.invest.reports import sdr_ndr_report_generator
from natcap.invest.reports import raster_utils
from natcap.invest.reports import report_constants


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """
    input_raster_plot_configs = [
        raster_utils.RasterPlotConfig(
            raster_path=args_dict['dem_path'],
            datatype='continuous',
            spec=model_spec.get_input('dem_path')),
        raster_utils.RasterPlotConfig(
            raster_path=args_dict['erodibility_path'],
            datatype='continuous',
            spec=model_spec.get_input('dem_path')),
        raster_utils.RasterPlotConfig(
            raster_path=args_dict['erosivity_path'],
            datatype='continuous',
            spec=model_spec.get_input('erosivity_path')),
        raster_utils.RasterPlotConfig(
            raster_path=args_dict['lulc_path'],
            datatype='nominal',
            spec=model_spec.get_input('lulc_path'))
    ]

    output_raster_plot_configs = [
        raster_utils.RasterPlotConfig(
            raster_path=file_registry['avoided_erosion'],
            datatype='continuous',
            spec=model_spec.get_output('avoided_erosion')),
        raster_utils.RasterPlotConfig(
            raster_path=file_registry['avoided_export'],
            datatype='continuous',
            spec=model_spec.get_output('avoided_export'),
            transform='log'),
        raster_utils.RasterPlotConfig(
            raster_path=file_registry['sed_deposition'],
            datatype='continuous',
            spec=model_spec.get_output('sed_deposition'),
            transform='log'),
        raster_utils.RasterPlotConfig(
            raster_path=file_registry['sed_export'],
            datatype='continuous',
            spec=model_spec.get_output('sed_export'),
            transform='log'),
        raster_utils.RasterPlotConfig(
            raster_path=file_registry['rkls'],
            datatype='continuous',
            spec=model_spec.get_output('rkls')),
        raster_utils.RasterPlotConfig(
            raster_path=file_registry['usle'],
            datatype='continuous',
            spec=model_spec.get_output('usle'),
            transform='log')
    ]

    masked_dem_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['pit_filled_dem'],
        datatype='continuous',
        spec=model_spec.get_output('pit_filled_dem'))
    what_drains_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['what_drains_to_stream'],
        datatype='binary',
        spec=model_spec.get_output('what_drains_to_stream'))
    stream_config = raster_utils.RasterPlotConfig(
        raster_path=file_registry['stream'],
        datatype='binary_high_contrast',
        spec=model_spec.get_output('stream'))
    stream_config.caption += report_constants.STREAM_CAPTION_APPENDIX
    intermediate_raster_plot_configs = [
        masked_dem_config, what_drains_config, stream_config]

    results_vector_id = 'watershed_results_sdr'
    results_vector_cols_to_sum = [
        'usle_tot', 'sed_export', 'sed_dep', 'avoid_exp', 'avoid_eros']

    sdr_ndr_report_generator.report(
        file_registry, args_dict, model_spec, target_html_filepath,
        input_raster_plot_configs, output_raster_plot_configs,
        intermediate_raster_plot_configs, results_vector_id,
        results_vector_cols_to_sum)
