from natcap.invest.reports import sdr_ndr_utils
from natcap.invest.reports import sdr_ndr_report_generator
from natcap.invest.reports import raster_utils

INPUT_RASTER_PLOT_TUPLES = [
    ('dem_path', 'continuous'),
    ('erodibility_path', 'continuous'),
    ('erosivity_path', 'continuous'),
    ('lulc_path', 'nominal'),
]

OUTPUT_RASTER_PLOT_TUPLES = [
    ('avoided_erosion', 'continuous', 'linear'),
    ('avoided_export', 'continuous', 'log'),
    ('sed_deposition', 'continuous', 'log'),
    ('sed_export', 'continuous', 'log'),
    ('rkls', 'continuous', 'linear'),
    ('usle', 'continuous', 'log'),
]

INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES = [
    ('pit_filled_dem', 'continuous'),
    ('what_drains_to_stream', 'binary'),
    ('stream', 'binary_high_contrast'),
]


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    input_raster_plot_configs = raster_utils.build_raster_plot_configs(
        args_dict, INPUT_RASTER_PLOT_TUPLES)

    output_raster_plot_configs = raster_utils.build_raster_plot_configs(
            file_registry, OUTPUT_RASTER_PLOT_TUPLES)

    intermediate_raster_plot_configs = raster_utils.build_raster_plot_configs(
            file_registry, INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES)

    raster_plot_configs = raster_utils.RasterPlotConfigGroup(
        input_raster_plot_configs,
        output_raster_plot_configs,
        intermediate_raster_plot_configs)

    input_raster_caption = raster_utils.generate_caption_from_raster_list(
        [(id, 'input') for (id, _) in INPUT_RASTER_PLOT_TUPLES],
        args_dict, file_registry, model_spec)
    output_raster_caption = raster_utils.generate_caption_from_raster_list(
        [(id, 'output') for (id, _, _) in OUTPUT_RASTER_PLOT_TUPLES],
        args_dict, file_registry, model_spec)
    intermediate_raster_caption = raster_utils.generate_caption_from_raster_list(
        [(id, 'output') for (id, _) in INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES],
        args_dict, file_registry, model_spec)
    intermediate_raster_caption = (
        sdr_ndr_utils.update_caption_with_stream_map_info(
            intermediate_raster_caption, args_dict['flow_dir_algorithm']))

    captions = raster_utils.RasterPlotCaptionGroup(
        inputs=input_raster_caption,
        outputs=output_raster_caption,
        intermediates=intermediate_raster_caption)

    results_vector_id = 'watershed_results_sdr'
    results_vector_cols_to_sum = [
        'usle_tot', 'sed_export', 'sed_dep', 'avoid_exp', 'avoid_eros']

    sdr_ndr_report_generator.report(
        file_registry, args_dict, model_spec, target_html_filepath,
        raster_plot_configs, captions,
        results_vector_id, results_vector_cols_to_sum)
