const HRA_ARGS = {
  aoi_vector_path: {
    argname: 'aoi_vector_path',
    value: 'something.shp',
    type: 'text',
    valid: false,
    validationRules: 'filepath',
    required: true,
  },
  criteria_table_path: {
    argname: 'criteria_table_path',
    value: '',
    type: 'text',
    valid: false,
    validationRules: 'filepath',
    required: true,
  },
  decay_eq: {
    argname: 'decay_eq',
    value: 'euclidean',
    type: 'select',
    options: ['euclidean', 'exponential'],
    valid: false,
    validationRules: 'select',
    required: true,
  },
  info_table_path: {
    argname: 'info_table_path',
    value: '',
    type: 'text',
    valid: false,
    validationRules: 'filepath',
    required: true,
  },
  max_rating: {
    argname: 'max_rating',
    value: '',
    type: 'text',
    valid: false,
    validationRules: 'integer',
    required: true,
  },
  resolution: {
    argname: 'resolution',
    value: '',
    type: 'text',
    valid: false,
    validationRules: 'integer',
    required: true,
  },
  risk_eq: {
    argname: 'risk_eq',
    value: 'linear',
    type: 'select',
    options: ['linear', 'multiplicative'],
    valid: false,
    validationRules: 'select',
    required: true,
  },
  results_suffix: {
    argname: 'results_suffix',
    value: '',
    type: 'text',
    valid: false,
    validationRules: 'string',
    required: false,
  },
  workspace_dir: {
    argname: 'workspace_dir',
    value: '',
    type: 'text',
    valid: false,
    validationRules: 'directory',
    required: true,
  },
  visualize_outputs: {
    argname: 'visualize_outputs',
    value: '',
    type: 'checkbox',
    valid: false,
    validationRules: 'checkbox',
    required: true,
  },
};

export default HRA_ARGS;