from pydantic import BaseModel


class Keyword(BaseModel):
    value: str
    vocabulary: str


class GCMDKeyword(Keyword):
    value: str
    uuid: str
    full_path: str
    vocabulary: str = 'Global Change Master Directory (GCMD) Keywords'


class InvestKeyword(Keyword):
    value: str
    vocabulary: str = 'InVEST Keywords'


BIOPHYSICAL_TABLE = InvestKeyword(value='BIOPHYSICAL TABLE')

CARBON = GCMDKeyword(
    value='CARBON',
    uuid='6f6537f5-773f-4df1-862b-d9ab80eb5e04',
    full_path='EARTH SCIENCE > BIOSPHERE > VEGETATION > CARBON')

CARBON_SEQUESTRATION = GCMDKeyword(
    value='CARBON SEQUESTRATION',
    uuid='e58872a8-6104-4ff8-bbca-4b00ba4b38e8',
    full_path='EARTH SCIENCE > BIOSPHERE > ECOLOGICAL DYNAMICS > ECOSYSTEM FUNCTIONS > CARBON SEQUESTRATION')

CARBON_SOIL = GCMDKeyword(
    value='CARBON',
    uuid='a7ae5843-479c-4055-b8fc-ba651e485750',
    full_path='EARTH SCIENCE > LAND SURFACE > SOILS > CARBON')

CROP_COEFFICIENT = InvestKeyword(value='CROP COEFFICIENT')

EVAPOTRANSPIRATION = GCMDKeyword(
    value='EVAPOTRANSPIRATION',
    uuid='26fc4850-7ba9-44d8-a156-5c623e17b72f',
    full_path='EARTH SCIENCE > ATMOSPHERE > ATMOSPHERIC WATER VAPOR > WATER VAPOR PROCESSES > EVAPOTRANSPIRATION')

HYDROELECTRIC_ENERGY = GCMDKeyword(
    value='HYDROELECTRIC ENERGY PRODUCTION/USE',
    uuid='7eba0eef-3a30-4282-a162-1f483370ddc4',
    full_path='EARTH SCIENCE > HUMAN DIMENSIONS > ECONOMIC RESOURCES > ENERGY PRODUCTION/USE > HYDROELECTRIC ENERGY PRODUCTION/USE')

LULC = GCMDKeyword(
    value='LAND USE/LAND COVER',
    uuid='e5815f58-8232-4c7f-b50d-ea71d73891a9',
    full_path='EARTH SCIENCE > LAND SURFACE > LAND USE/LAND COVER')

LULC_CLASSES = GCMDKeyword(
    value='LAND USE/LAND COVER CLASSES',
    uuid='e5815f58-8232-4c7f-b50d-ea71d73891a9',
    full_path='EARTH SCIENCE > LAND SURFACE > LAND USE/LAND COVER > LAND USE/LAND COVER CLASSES')   

PAWC = InvestKeyword(value='PLANT AVAILABLE WATER CONTENT')

PRECIPITATION = GCMDKeyword(
    value='PRECIPITATION',
    uuid='1532e590-a62d-46e3-8d03-2351bc48166a',
    full_path='EARTH SCIENCE > ATMOSPHERE > PRECIPITATION')

PRECIPITATION_RATE = GCMDKeyword(
    value='PRECIPITATION_RATE',
    uuid='ac50c468-df2f-429c-8394-9d63efcc6f9d',
    full_path='EARTH SCIENCE > ATMOSPHERE > PRECIPITATION > PRECIPITATION_RATE')

REFERENCE_EVAPOTRANSPIRATION = InvestKeyword(value='REFERENCE_EVAPOTRANSPIRATION')

SOIL_ROOTING_DEPTH = GCMDKeyword(
    value='SOIL ROOTING DEPTH',
    uuid='1b475201-a032-4a66-a3aa-a35605affaee',
    full_path='EARTH SCIENCE > LAND SURFACE > SOILS > SOIL ROOTING DEPTH')

WATERSHED_BOUNDARIES = GCMDKeyword(
    value='WATERSHED BOUNDARIES',
    uuid='b98123fc-6a87-4396-8e1a-ae7406e76ff6',
    full_path='EARTH SCIENCE > TERRESTRIAL HYDROSPHERE > SURFACE WATER > WATERSHED CHARACTERISTICS > WATERSHED BOUNDARIES')

WATER_BUDGET = GCMDKeyword(
    value='WATER BUDGET',
    uuid='f8702aed-a0ae-46f0-89eb-abde858bc6ac',
    full_path='EARTH SCIENCE > TERRESTRIAL HYDROSPHERE > WATER BUDGET')
