import logging
import time

import altair
import geopandas
from matplotlib.colors import ListedColormap
from pint import Unit

from natcap.invest import __version__
from natcap.invest import gettext
from natcap.invest.reports import jinja_env, raster_utils, report_constants, vector_utils
from natcap.invest.reports.raster_utils import RasterDatatype, RasterPlotConfig
from natcap.invest.reports.sdr_ndr_utils import generate_results_table_from_vector
from natcap.invest.reports.vector_utils import get_vector_attr_table_caption
from natcap.invest.spec import format_unit, ModelSpec
from natcap.invest.unit_registry import u
from natcap.invest.utils import read_csv_to_dataframe

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/urban_cooling.html')

def _create_map(geodataframe: geopandas.GeoDataFrame, xy_ratio: float,
                attribute: str, title: str, units: Unit, scale: altair.Scale,
                map_width: int) -> altair.Chart:
    """Create a choropleth map from the provided data and specifications."""
    return altair.Chart(geodataframe).mark_geoshape(
        stroke="white",
        strokeWidth=0.5,
        tooltip=True
    ).project(
        type='identity',
        reflectY=True
    ).encode(
        color=altair.Color(attribute, scale=scale)
    ).properties(
        width=map_width,
        height=map_width / xy_ratio,
        title=altair.TitleParams(
                text=f'{title} ({format_unit(units)})',
                fontSize=18,
                subtitle=gettext('Attribute: ') + attribute,
                subtitleFontSize=16,
                offset=16
            )
    )


def _get_energy_sav_units(args_dict: dict) -> Unit:
    energy_consumption_df = read_csv_to_dataframe(
        args_dict['energy_consumption_table_path'])
    energy_cols = [col.lower() for col in energy_consumption_df.columns]
    return u.currency if 'cost' in energy_cols else u.kilowatt_hour


def _create_aoi_maps(
            model_spec: ModelSpec,
            file_registry: dict[str, str],
            args_dict: dict
        ) -> tuple[str | None, list[str] | None, list[str] | None]:
    """Create AOI maps and caption.

    Individual choropleth maps are created and concatenated, allowing them to
    share the same datasource (in this case, the ``'uhi_results'`` vector
    output).

    Maps are generated only for attributes that have non-``None`` values, e.g.,
    if the model was run with ``'do_energy_valuation'=False``, then no "Avoided
    Energy Consumption" map is created.

    If the AOI has only one feature, no maps are generated, since
    single-feature choropleth maps aren't typically useful.

    Args:
        model_spec (ModelSpec): the Urban Cooling model spec.
        file_registry (dict[str, str]): the file registry generated by the
            model run.
        args_dict (dict): inputs to the model run.

    Returns:
        (tuple[str | None, list[str] | None, list[str] | None)
        - map_json (str): JSON representation of the compound map suitable for
            passing to the ``embed_vega`` macro, or ``None`` if the AOI has
            only one feature.
        - caption (list[str]): a list of caption strings (one for each component
            map) suitable for passing to the ``caption`` macro with
            ``definition_list=True``, or ``None`` if the AOI has only one
            feature.
        - source_list (list[str]): a list of source files suitable for passing
            to the ``caption`` macro, or ``None`` if the AOI has only one
            feature.
    """
    agg_uhi_results = geopandas.read_file(
        file_registry['uhi_results'], engine='fiona')

    # Do not plot AOI maps when there is only one feature.
    num_features = len(agg_uhi_results)
    if num_features <= 1:
        return (None, None, None)

    uhi_output_spec = model_spec.get_output('uhi_results')
    uhi_effect = args_dict['uhi_max']
    TITLES_UNITS_SCALES = {
        'avg_cc': (
            gettext('Average Cooling Capacity'),
            uhi_output_spec.get_field('avg_cc').units,
            altair.Scale(scheme='blues')
        ),
        'avg_tmp_v': (
            gettext('Average Air Temperature'),
            uhi_output_spec.get_field('avg_tmp_v').units,
            altair.Scale(scheme='yelloworangered')
        ),
        'avg_tmp_an': (
            gettext('Average Air Temperature Anomaly'),
            uhi_output_spec.get_field('avg_tmp_an').units,
            altair.Scale(domain={'unionWith': [-1 * uhi_effect, uhi_effect]},
                         domainMid=0, scheme='redyellowblue', reverse=True)
        ),
        'avg_wbgt_v': (
            gettext('Average Wet Bulb Globe Temperature (WBGT)'),
            uhi_output_spec.get_field('avg_wbgt_v').units,
            altair.Scale(scheme='yelloworangered')
        ),
        'avg_ltls_v': (
            gettext('Light Work Productivity Loss'),
            uhi_output_spec.get_field('avg_ltls_v').units,
            altair.Scale(domain=[0, 100], scheme='purples')
        ),
        'avg_hvls_v': (
            gettext('Heavy Work Productivity Loss'),
            uhi_output_spec.get_field('avg_hvls_v').units,
            altair.Scale(domain=[0, 100], scheme='purples')
        ),
        'avd_eng_cn': (
            gettext('Avoided Energy Consumption'),
            _get_energy_sav_units(args_dict),
            altair.Scale(scheme='greens')
        )
    }

    attr_list = ['avg_cc', 'avg_tmp_v', 'avg_tmp_an']
    if args_dict['do_productivity_valuation']:
        attr_list.extend(['avg_wbgt_v', 'avg_ltls_v', 'avg_hvls_v'])
    if args_dict['do_energy_valuation']:
        attr_list.extend(['avd_eng_cn'])

    caption = vector_utils.get_vector_attr_table_caption(
        uhi_output_spec, attr_list)
    source_list = [uhi_output_spec.path]

    _, xy_ratio = vector_utils.get_geojson_bbox(agg_uhi_results)

    def _create_aoi_map(attribute: str, title: str, units: Unit,
                        scale: altair.Scale) -> altair.Chart:
        return _create_map(agg_uhi_results, xy_ratio, attribute, title, units,
                           scale, map_width=250)

    aoi_maps = [_create_aoi_map(attr, *TITLES_UNITS_SCALES[attr])
                for attr in attr_list]

    compound_map = altair.concat(
        *aoi_maps,
        columns=3
    ).configure_concat(
        spacing=64
    ).configure_legend(
        title=None,
        **vector_utils.LEGEND_CONFIG
    ).resolve_scale(
        color='independent'
    )

    return (compound_map.to_json(), caption, source_list)

def _create_bldg_maps(
            model_spec: ModelSpec,
            file_registry: dict[str, str],
            args_dict: dict
        ) -> tuple[str | None, list[str] | None, list[str] | None]:
    """Create building stats maps and caption.

    Individual choropleth maps are created and concatenated, allowing them to
    share the same datasource (in this case, the ``'buildings_with_stats'``
    vector output).

    It is assumed that the ``'buildings_with_stats'`` output exists. If the
    output does not exist (e.g., if the model was run with
    ``'do_energy_valuation'=False``), do not call this function.

    Args:
        model_spec (ModelSpec): the Urban Cooling model spec.
        file_registry (dict[str, str]): the file registry generated by the
            model run.
        args_dict (dict): inputs to the model run.

    Returns:
        (tuple[str, list[str], list[str])
        - map_json (str): JSON representation of the compound map suitable for
            passing to the ``embed_vega`` macro.
        - caption (list[str]): a list of caption strings (one for each component
            map) suitable for passing to the ``caption`` macro with
            ``definition_list=True``.
        - source_list (list[str]): a list of source files suitable for passing
            to the ``caption`` macro.
    """
    bldg_output_spec = model_spec.get_output('buildings_with_stats')
    attr_list = ['energy_sav', 'mean_t_air']
    bldg_map_caption = vector_utils.get_vector_attr_table_caption(
        bldg_output_spec, attr_list)
    bldg_map_source_list = [bldg_output_spec.path]

    TITLES_UNITS_SCALES = {
        'energy_sav': (
            gettext('Energy Savings by Building'),
            _get_energy_sav_units(args_dict),
            altair.Scale(scheme='greens')
        ),
        'mean_t_air': (
            gettext('Average Air Temperature by Building'),
            bldg_output_spec.get_field('mean_t_air').units,
            altair.Scale(scheme='yelloworangered')
        )
    }

    agg_bldg_results = geopandas.read_file(
        file_registry['buildings_with_stats'], engine='fiona')
    _, xy_ratio = vector_utils.get_geojson_bbox(agg_bldg_results)

    def _create_bldg_map(attribute: str, title: str, units: Unit,
                        scale: altair.Scale) -> altair.Chart:
        return _create_map(agg_bldg_results, xy_ratio, attribute, title, units,
                           scale, map_width=550)

    bldg_maps = [_create_bldg_map(attr, *TITLES_UNITS_SCALES[attr])
                for attr in attr_list]

    compound_map = altair.concat(
        *bldg_maps,
        columns=2
    ).configure_concat(
        spacing=64
    ).configure_legend(
        title=None,
        **vector_utils.LEGEND_CONFIG
    ).resolve_scale(
        color='independent'
    )

    return (compound_map.to_json(), bldg_map_caption, bldg_map_source_list)

def report(file_registry: dict[str, str], args_dict: dict,
           model_spec: ModelSpec, target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    # Input rasters: LULC, reference evapotranspiration
    input_raster_heading = gettext(
        'Input Rasters: LULC and Reference Evapotranspiration')
    input_raster_plot_configs = [
        RasterPlotConfig(args_dict['lulc_raster_path'],
                         RasterDatatype.nominal,
                         model_spec.get_input('lulc_raster_path')),
        RasterPlotConfig(args_dict['ref_eto_raster_path'],
                         RasterDatatype.continuous,
                         model_spec.get_input('ref_eto_raster_path'),
                         colormap='Greens'),
    ]
    inputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        input_raster_plot_configs)
    input_raster_caption = raster_utils.caption_raster_list(
        input_raster_plot_configs)

    # Primary raster outputs: air temperature, heat mitigation index
    output_raster_heading = gettext(
        'Air Temperature and Heat Mitigation Index')
    output_raster_plot_configs = [
        RasterPlotConfig(file_registry['t_air'], RasterDatatype.continuous,
                         model_spec.get_output('t_air'), colormap='YlOrRd'),
        RasterPlotConfig(file_registry['hm'], RasterDatatype.continuous,
                         model_spec.get_output('hm'), colormap='Greens'),
    ]
    outputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        output_raster_plot_configs)
    output_raster_caption = raster_utils.caption_raster_list(
        output_raster_plot_configs)

    # Primary vector output: uhi_results
    uhi_table = generate_results_table_from_vector(
        file_registry['uhi_results'])
    uhi_table_caption = get_vector_attr_table_caption(
        model_spec.get_output('uhi_results'))
    (
        aoi_map_json,
        aoi_map_caption,
        aoi_map_source_list
    ) = _create_aoi_maps(model_spec, file_registry, args_dict)

    # Optional vector output: buildings_with_stats
    if 'buildings_with_stats' in file_registry:
        # Limit columns to the index column (whose name may vary)
        # and the model-defined columns 'energy_sav' and 'mean_t_air'.
        bldg_table_cols = [0, 'energy_sav', 'mean_t_air']
        bldg_table_cols_to_sum = ['energy_sav']
        (bldg_table, bldg_totals_table) = generate_results_table_from_vector(
            file_registry['buildings_with_stats'],
            target_cols=bldg_table_cols,
            cols_to_sum=bldg_table_cols_to_sum)
        bldg_table_caption = get_vector_attr_table_caption(
            model_spec.get_output('buildings_with_stats'))
        (
            bldg_map_json,
            bldg_map_caption,
            bldg_map_source_list
        ) = _create_bldg_maps(model_spec, file_registry, args_dict)
    else:
        bldg_table = None
        bldg_totals_table = None
        bldg_table_caption = None
        bldg_map_json = None
        bldg_map_caption = None
        bldg_map_source_list = None

    # Secondary raster outputs: cooling capacity (always);
    # building intensity ('intensity' method);
    # ETI, shade, albedo ('factors' method)
    green_area_colormap = ListedColormap(["#ccccd5", "#006500"])
    biophysical_heading = gettext('Biophysical Maps')
    biophysical_raster_plot_configs = [
        RasterPlotConfig(file_registry['cc'], RasterDatatype.continuous,
                         model_spec.get_output('cc'), colormap='Blues'),
        RasterPlotConfig(file_registry['green_area'], RasterDatatype.binary,
                         model_spec.get_output('green_area'),
                         colormap=green_area_colormap),
    ]
    if args_dict['cc_method'] == 'intensity':
        biophysical_raster_plot_configs.extend([
            RasterPlotConfig(file_registry['building_intensity'],
                             RasterDatatype.continuous,
                             model_spec.get_output('building_intensity'),
                             colormap='Reds'),
        ])
    else:
        biophysical_raster_plot_configs.extend([
            RasterPlotConfig(file_registry['eti'], RasterDatatype.continuous,
                            model_spec.get_output('eti'), colormap='Greens'),
            RasterPlotConfig(file_registry['shade'],
                             RasterDatatype.continuous,
                             model_spec.get_output('shade'),
                             colormap='Blues'),
            RasterPlotConfig(file_registry['albedo'],
                             RasterDatatype.continuous,
                             model_spec.get_output('albedo'),
                             colormap='Blues'),
        ])
    biophysical_img_src = raster_utils.plot_and_base64_encode_rasters(
        biophysical_raster_plot_configs)
    biophysical_raster_caption = raster_utils.caption_raster_list(
        biophysical_raster_plot_configs)

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict, model_spec).to_html(na_rep='')

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            uhi_table=uhi_table,
            uhi_table_caption=uhi_table_caption,
            aoi_map_json=aoi_map_json,
            aoi_map_caption=aoi_map_caption,
            aoi_map_source_list=aoi_map_source_list,
            bldg_table=bldg_table,
            bldg_totals_table=bldg_totals_table,
            bldg_table_caption=bldg_table_caption,
            bldg_map_json=bldg_map_json,
            bldg_map_caption=bldg_map_caption,
            bldg_map_source_list=bldg_map_source_list,
            input_raster_heading=input_raster_heading,
            inputs_img_src=inputs_img_src,
            inputs_caption=input_raster_caption,
            lulc_pre_caption=report_constants.LULC_PRE_CAPTION,
            output_raster_heading=output_raster_heading,
            outputs_img_src=outputs_img_src,
            outputs_caption=output_raster_caption,
            biophysical_heading=biophysical_heading,
            biophysical_img_src=biophysical_img_src,
            biophysical_raster_caption=biophysical_raster_caption,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
