import logging
import time

import altair
import geopandas
from matplotlib.colors import ListedColormap

from natcap.invest import __version__
from natcap.invest import gettext
from natcap.invest.reports import jinja_env, raster_utils, report_constants, vector_utils
from natcap.invest.reports.raster_utils import RasterDatatype, RasterPlotConfig
from natcap.invest.reports.sdr_ndr_utils import generate_results_table_from_vector
from natcap.invest.spec import ModelSpec

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/urban_cooling.html')

MAP_WIDTH = 250 # pixels


def _create_aggregate_map(geodataframe, xy_ratio, attribute,
                          title, scale: altair.Scale):
    attr_map = altair.Chart(geodataframe).mark_geoshape(
        stroke="white",
        strokeWidth=0.5
    ).project(
        type='identity',
        reflectY=True
    ).encode(
        color=altair.Color(attribute, scale=scale),
        tooltip=[altair.Tooltip(attribute, title=attribute)]
    ).properties(
        width=MAP_WIDTH,
        height=MAP_WIDTH / xy_ratio,
        title=title
    ).configure_title(
        fontSize=16,
    ).configure_legend(title=None, **vector_utils.LEGEND_CONFIG)

    return attr_map.to_json()


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    # Input rasters: LULC, reference evapotranspiration
    input_raster_heading = 'LULC and Reference Evapotranspiration Maps'
    input_raster_plot_configs = [
        RasterPlotConfig(args_dict['lulc_raster_path'],
                         RasterDatatype.nominal,
                         model_spec.get_input('lulc_raster_path')),
        RasterPlotConfig(args_dict['ref_eto_raster_path'],
                         RasterDatatype.continuous,
                         model_spec.get_input('ref_eto_raster_path'),
                         colormap='viridis'),
    ]
    inputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        input_raster_plot_configs)
    input_raster_caption = raster_utils.caption_raster_list(
        input_raster_plot_configs)

    # Key raster output: heat mitigation index
    output_raster_heading = 'Heat Mitigation Index'
    output_raster_plot_configs = [
        RasterPlotConfig(file_registry['hm'], RasterDatatype.ratio,
                         model_spec.get_output('hm'), colormap='Blues'),
    ]
    outputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        output_raster_plot_configs)
    output_raster_caption = raster_utils.caption_raster_list(
        output_raster_plot_configs)

    # Key vector output: uhi_results
    agg_table_cols_to_sum = ['avg_cc', 'avg_tmp_v', 'avg_tmp_an', 'avd_eng_cn',
                             'avg_wbgt_v', 'avg_ltls_v', 'avg_hvls_v']
    (agg_table, agg_totals_table) = generate_results_table_from_vector(
        file_registry['uhi_results'], agg_table_cols_to_sum)

    uhi_output = model_spec.get_output('uhi_results')
    agg_uhi_results = geopandas.read_file(file_registry['uhi_results'])
    _, xy_ratio = vector_utils.get_geojson_bbox(agg_uhi_results)
    cc_map_json = _create_aggregate_map(
        agg_uhi_results, xy_ratio, 'avg_cc',
        gettext('Average Cooling Capacity'),
        altair.Scale(domain=[0, 1], scheme='blues'))
    cc_map_caption = (uhi_output.get_field('avg_cc').about)
    ref_temp = args_dict['t_ref']
    uhi_effect = args_dict['uhi_max']
    air_temp_map_json = _create_aggregate_map(
        agg_uhi_results, xy_ratio, 'avg_tmp_v',
        gettext('Average Air Temperature'),
        altair.Scale(
            domain={'unionWith': [
                ref_temp - uhi_effect, ref_temp + uhi_effect]},
            domainMid=ref_temp, scheme='redyellowblue', reverse=True))
    air_temp_map_caption = (uhi_output.get_field('avg_tmp_v').about)
    air_temp_anomaly_map_json = _create_aggregate_map(
        agg_uhi_results, xy_ratio, 'avg_tmp_an',
        gettext('Average Air Temperature Anomaly'),
        altair.Scale(domain={'unionWith': [-1 * uhi_effect, uhi_effect]},
                     domainMid=0, scheme='redyellowblue', reverse=True))
    air_temp_anomaly_map_caption = (uhi_output.get_field('avg_tmp_an').about)
    uhi_map_source_list = [model_spec.get_output('uhi_results').path]

    # Key intermediate raster outputs: cooling capacity, air temperature
    intermediate_heading_1 = gettext('Cooling Capacity and Air Temperature Maps')
    intermediate_raster_plot_configs_1 = [
        RasterPlotConfig(file_registry['cc'], RasterDatatype.ratio,
                         model_spec.get_output('cc'), colormap='Blues'),
        RasterPlotConfig(file_registry['t_air'], RasterDatatype.continuous,
                         model_spec.get_output('t_air'), colormap='RdYlBu_r'),
    ]
    intermediate_img_src_1 = raster_utils.plot_and_base64_encode_rasters(
        intermediate_raster_plot_configs_1)
    intermediate_raster_caption_1 = raster_utils.caption_raster_list(
        intermediate_raster_plot_configs_1)

    # Additional intermediate raster outputs: kc, green area (always),
    # building intensity ('intensity' method),
    # shade, albedo ('factors' method)
    green_area_colormap = ListedColormap(["#ccccd5", "#006500"])
    # green_area_colormap = ListedColormap(["#000000", "#008900"])
    intermediate_heading_2 = gettext('Biophysical Maps')
    intermediate_raster_plot_configs_2 = [
        RasterPlotConfig(file_registry['kc'], RasterDatatype.continuous,
                         model_spec.get_output('kc'), colormap='viridis'),
        RasterPlotConfig(file_registry['green_area'], RasterDatatype.binary,
                         model_spec.get_output('green_area'),
                         colormap=green_area_colormap),
    ]

    if args_dict['cc_method'] == 'intensity':
        intermediate_raster_plot_configs_2.extend([
            RasterPlotConfig(file_registry['building_intensity'],
                             RasterDatatype.ratio,
                             model_spec.get_output('building_intensity'),
                             colormap='Reds'),
        ])
    else:
        intermediate_raster_plot_configs_2.extend([
            RasterPlotConfig(file_registry['shade'],
                             RasterDatatype.ratio,
                             model_spec.get_output('shade'),
                             colormap='Blues'),
            RasterPlotConfig(file_registry['albedo'],
                             RasterDatatype.ratio,
                             model_spec.get_output('albedo'),
                             colormap='Blues'),
        ])
    intermediate_img_src_2 = raster_utils.plot_and_base64_encode_rasters(
        intermediate_raster_plot_configs_2)
    intermediate_raster_caption_2 = raster_utils.caption_raster_list(
        intermediate_raster_plot_configs_2)

    intermediate_raster_sections = [
        {'heading': heading, 'img_src': img_src, 'caption': caption}
        for (heading, img_src, caption)
        in zip([intermediate_heading_1, intermediate_heading_2],
               [intermediate_img_src_1, intermediate_img_src_2],
               [intermediate_raster_caption_1, intermediate_raster_caption_2])
    ]

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict, model_spec).to_html(na_rep='')

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            agg_table=agg_table,
            agg_totals_table=agg_totals_table,
            cc_map_json=cc_map_json,
            cc_map_caption=cc_map_caption,
            air_temp_map_json=air_temp_map_json,
            air_temp_map_caption=air_temp_map_caption,
            air_temp_anomaly_map_json=air_temp_anomaly_map_json,
            air_temp_anomaly_map_caption=air_temp_anomaly_map_caption,
            uhi_map_source_list=uhi_map_source_list,
            input_raster_heading=input_raster_heading,
            inputs_img_src=inputs_img_src,
            inputs_caption=input_raster_caption,
            lulc_pre_caption=report_constants.LULC_PRE_CAPTION,
            output_raster_heading=output_raster_heading,
            outputs_img_src=outputs_img_src,
            outputs_caption=output_raster_caption,
            intermediate_raster_sections=intermediate_raster_sections,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
