import logging
import os
import time

import pandas

from natcap.invest import __version__
from natcap.invest import gettext
from natcap.invest.reports import jinja_env, raster_utils, report_constants
from natcap.invest.reports.raster_utils import RasterDatatype, RasterPlotConfig
from natcap.invest.spec import ModelSpec

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/carbon.html')

_CARBON_POOLS = ['above', 'below', 'dead', 'soil']


def _get_intermediate_output_headings(args_dict: dict) -> list[str]:
    """Get headings for Intermediate Outputs sections of the report.

    Args:
        args_dict (dict): the arguments passed to the model's ``execute``
            function.

    Returns:
        A list containing exactly one string or exactly four strings.
        If the model was run with ``calc_sequestration = False``, the report
        will group all four intermediate outputs into one section, with the
        heading "Carbon Maps by Pool Type".
        If the model was run with ``calc_sequestration = True``, the report
        will group intermediate outputs by carbon pool type, resulting in four
        sections containing two rasters each. This structure facilitates
        side-by-side comparisons of baseline vs. alternate scenarios for each
        carbon pool type.
    """
    if args_dict['calc_sequestration']:
        # make sure this order matches order of `_CARBON_POOLS`
        return [
            gettext('Carbon Maps: Aboveground'),
            gettext('Carbon Maps: Belowground'),
            gettext('Carbon Maps: Dead'),
            gettext('Carbon Maps: Soil'),
        ]
    else:
        return [gettext('Carbon Maps by Pool Type')]


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """
    lulc_raster_list = [args_dict['lulc_bas_path']]
    lulc_caption = [
        f"{os.path.basename(args_dict['lulc_bas_path'])}:{model_spec.get_input('lulc_bas_path').about}"]

    output_raster_config_list = [
        RasterPlotConfig(
            raster_path=file_registry['c_storage_bas'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output('c_storage_bas'))]

    intermediate_raster_config_lists = [[
        RasterPlotConfig(
            raster_path=file_registry[f'c_{pool_type}_bas'],
            datatype=RasterDatatype.continuous,
            spec=model_spec.get_output(f'c_{pool_type}_bas'))
        for pool_type in _CARBON_POOLS]]

    if args_dict['calc_sequestration']:
        lulc_raster_list.append(args_dict['lulc_alt_path'])
        lulc_caption.append(
            f"{os.path.basename(args_dict['lulc_alt_path'])}:{model_spec.get_input('lulc_alt_path').about}")

        output_raster_config_list.extend([
            RasterPlotConfig(
                raster_path=file_registry['c_storage_alt'],
                datatype=RasterDatatype.continuous,
                spec=model_spec.get_output('c_storage_alt')),
            RasterPlotConfig(
                raster_path=file_registry['c_change_bas_alt'],
                datatype=RasterDatatype.divergent,
                spec=model_spec.get_output('c_change_bas_alt'))])

        intermediate_raster_config_lists = [[
            RasterPlotConfig(
                raster_path=file_registry[f'c_{pool_type}_bas'],
                datatype=RasterDatatype.continuous,
                spec=model_spec.get_output(f'c_{pool_type}_bas')),
            RasterPlotConfig(
                raster_path=file_registry[f'c_{pool_type}_alt'],
                datatype=RasterDatatype.continuous,
                spec=model_spec.get_output(f'c_{pool_type}_alt')),
         ] for pool_type in _CARBON_POOLS]

    if args_dict['do_valuation']:
        output_raster_config_list.append(
            RasterPlotConfig(
                raster_path=file_registry['npv_alt'],
                datatype=RasterDatatype.divergent,
                spec=model_spec.get_output('npv_alt')))

    outputs_img_src = raster_utils.plot_and_base64_encode_rasters(
        output_raster_config_list)
    output_raster_caption = raster_utils.caption_raster_list(
        output_raster_config_list)

    # There can be multiple sections for intermediate rasters
    intermediate_img_srcs = [raster_utils.plot_and_base64_encode_rasters(
        config_list) for config_list in intermediate_raster_config_lists]
    intermediate_raster_captions = [raster_utils.caption_raster_list(
        config_list) for config_list in intermediate_raster_config_lists]

    intermediate_headings = _get_intermediate_output_headings(args_dict)

    intermediate_raster_sections = [
        {'heading': heading, 'img_src': img_src, 'caption': caption}
        for (heading, img_src, caption)
        in zip(intermediate_headings,
               intermediate_img_srcs,
               intermediate_raster_captions)
    ]

    lulc_img_src, lulc_legend_html = raster_utils.plot_categorical_raster_with_table(
        lulc_raster_list)

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict, model_spec).to_html(na_rep='')

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    agg_results_df = pandas.read_csv(file_registry['summary_csv'], index_col=0)
    agg_results_df.index.rename(None, inplace=True)
    agg_results_table = agg_results_df.to_html()

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            agg_results_table=agg_results_table,
            lulc_caption=lulc_caption,
            lulc_img_src=lulc_img_src,
            lulc_legend_html=lulc_legend_html,
            outputs_img_src=outputs_img_src,
            outputs_caption=output_raster_caption,
            intermediate_raster_sections=intermediate_raster_sections,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
