name: Release (Part 2 of 2)

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.AUTORELEASE_BOT_PAT }}

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          # Workaround for setuptools generating invalid metadata
          # https://github.com/natcap/invest/issues/1913
          pip install "twine>=6.1.0"
          pip install -U packaging

      - name: Get version from manual trigger input
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "AUTORELEASE_BRANCH=autorelease/${{ inputs.version }}" >> $GITHUB_ENV

      - name: Find actions run for the $VERSION tag
        run: |
          echo "RUN_ID=$( \
            gh run list \
              --branch $VERSION \
              --workflow 'Run Tests and Build' \
              --limit 1 \
              --json databaseId \
              --jq .[].databaseId)" >> $GITHUB_ENV

      - name: Download release artifacts
        run: |
          mkdir artifacts
          # this will download a folder containing each artifact
          gh run download $RUN_ID --dir artifacts --pattern "Wheel for *"
          # move the artifacts out of the folders
          mv artifacts/*/* artifacts
          rm -rf artifacts/Wheel*

          # download each artifact separately so that the command will fail if any is missing
          for artifact in InVEST-sample-data \
                          InVEST-user-guide \
                          "Source distribution"
          do
            gh run download $RUN_ID --dir artifacts --name "$artifact"
          done

          # download the signed workbench files from GCS
          wget --directory-prefix=artifacts https://storage.googleapis.com/releases.naturalcapitalproject.org/invest/${{ env.VERSION }}/workbench/invest_${{ env.VERSION }}_workbench_win32_x64.exe
          wget --directory-prefix=artifacts https://storage.googleapis.com/releases.naturalcapitalproject.org/invest/${{ env.VERSION }}/workbench/invest_${{ env.VERSION }}_workbench_darwin_x64.dmg

      - name: Create release notes
        shell: python
        run: |
          import os
          import re
          with open('notes.rst', 'w') as notes:
              notes.write('This release includes the following fixes and features:\n\n')
              with open('HISTORY.rst') as f:
                  do_write = False
                  for line in f.readlines():
                      # match the header starting with $VERSION
                      if line.startswith(os.environ['VERSION']):
                          do_write = True
                      # match the header pattern X.XX.X (XXXX-XX-XX)
                      # using \w to allow for alpha and post releases
                      elif re.match(r'\d+\.\d+\.\w+ \(\d{4}-\d{2}-\d{2}\)', line):
                          do_write = False
                      if do_write:
                          notes.write(line)

      - name: Create Github release
        run: |
          gh release create $VERSION \
            --verify-tag \
            --title $VERSION \
            --notes-file notes.rst \
            artifacts/*

      - name: Create a PR from the autorelease branch into main
        run: |
          gh pr create \
            --base main \
            --head $AUTORELEASE_BRANCH \
            --title "$VERSION release" \
            --reviewer $GITHUB_ACTOR \
            --assignee $GITHUB_ACTOR \
            --body "
            # Merge $AUTORELEASE_BRANCH into \`main\`

            This PR contains automated changes made for the $VERSION release.
            It was created by Part 2 of the automated release workflow.

            Changes on the $AUTORELEASE_BRANCH branch should have already been
            reviewed before the Part 2 workflow was run, and the release should
            have been published automatically. Merging this PR is the final
            manual step after the release has happened."

      - name: Create a PyPI release
        # this is the only step that can't be rolled back
        run: |
          twine upload \
            --username="__token__" \
            --password=${{ secrets.PYPI_NATCAP_INVEST_TOKEN }} \
            artifacts/natcap_invest*
