name: Release (Part 1 of 2)

on:
  schedule:
    # every tuesday at 6:20pm UTC (10:20am PST / 11:20am PDT)
    # cron doesn't support "first tuesday of the month", so we will use github
    # actions syntax below to skip tuesdays that aren't in the first week.
    # it is recommended not to start on the hour to avoid peak traffic
    - cron: "20 18 * * 2"
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  VERSION: ${{ inputs.version }}
  # use a personal access token here which has permissions to trigger further actions
  # this is necessary for the pr checks
  GITHUB_TOKEN: ${{ secrets.AUTORELEASE_BOT_PAT }}

jobs:
  start-release:
    if: github.repository_owner == 'natcap'
    runs-on: ubuntu-latest
    steps:
      # skip scheduled runs that aren't the first tuesday of the month
      - name: Check day of month
        run: |
          if [[ $GITHUB_EVENT_NAME == "workflow_dispatch" || $(date +%d) -le 7 ]]; then
            echo "RUN=true" >> $GITHUB_ENV
          else
            echo "RUN=false" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4
        if: env.RUN == 'true'
        with:
          fetch-depth: 0  # fetch entire history, for versioning
          token: ${{ secrets.AUTORELEASE_BOT_PAT }}

      - name: Install dependencies
        if: env.RUN == 'true'
        run: pip install rst2html5 setuptools_scm

      # Assuming there has been at least one commit since the last tag,
      # the bugfix number in the setuptools_scm version will be one
      # greater than that of the last tag.
      # https://setuptools-scm.readthedocs.io/en/latest/usage/#default-versioning-scheme
      - name: Get current version number (scheduled runs only)
        if: env.RUN == 'true' && github.event_name == 'schedule'
        run: echo "SETUPTOOLS_SCM_VERSION=$(python -m setuptools_scm)" > $GITHUB_ENV

      - name: Get next bugfix version number (scheduled runs only)
        if: env.RUN == 'true' && github.event_name == 'schedule'
        shell: python
        run: |
          import os
          major, minor, bugfix, *_ = os.environ['SETUPTOOLS_SCM_VERSION'].split('.')
          with open(os.environ['GITHUB_ENV'], "a") as env_file:
            env_file.write(f'VERSION={major}.{minor}.{bugfix}')

      - name: Configure git and define branch name
        if: env.RUN == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          echo "AUTORELEASE_BRANCH=autorelease/$VERSION" > $GITHUB_ENV

      # Members of the natcap software team can push to the autorelease branch on
      # natcap/invest; this branch is a special case for our release process.
      - name: Create autorelease branch
        if: env.RUN == 'true'
        run: git checkout -b "$AUTORELEASE_BRANCH"

      # Replace
      #
      # Unreleased Changes
      # ------------------
      #
      # with
      #
      # ..
      #   Unreleased Changes
      #   ------------------
      #
      # X.X.X (XXXX-XX-XX)
      # ------------------
      - name: Update HISTORY.rst
        if: env.RUN == 'true'
        run: |
          HEADER="$VERSION ($(date '+%Y-%m-%d'))"
          HEADER_LENGTH=${#HEADER}
          UNDERLINE=$(for i in $(seq 1 $HEADER_LENGTH); do echo -n "-"; done)
          perl -0777 -i -pe \
              "s/Unreleased Changes\n------------------/..\n  Unreleased Changes\n  ------------------\n\n${HEADER}\n${UNDERLINE}/g" \
              HISTORY.rst

      - name: Generate changelog.html
        if: env.RUN == 'true'
        run: rst2html5 HISTORY.rst workbench/changelog.html

      - name: Update package.json version
        if: env.RUN == 'true'
        uses: BellCubeDev/update-package-version-by-release-tag@v2
        with:
          version: ${{ env.VERSION }}
          ignore-semver-check: "true"  # allow PEP 440 alpha/beta/rc releases
          package-json-path: workbench/package.json

      - name: Update CITATION.cff
        if: env.RUN == 'true'
        run: python scripts/update-citation-cff.py CITATION.cff $VERSION $(date '+%Y-%m-%d')

      - name: Commit updated HISTORY.rst, changelog.html, package.json and CITATION.cff
        if: env.RUN == 'true'
        run: |
          git add HISTORY.rst
          git add workbench/changelog.html
          git add workbench/package.json
          git add CITATION.cff
          git commit -m "Committing the $VERSION release."

      - name: Tag and push
        if: env.RUN == 'true'
        run: |
          git tag $VERSION
          git push --atomic origin $AUTORELEASE_BRANCH $VERSION

      - name: Find actions run for the version tag
        if: env.RUN == 'true'
        run: |
          # wait a few seconds to make sure the actions run exists before querying it
          sleep 5
          echo "TAG_RUN_URL=$( \
            gh run list \
              --branch $VERSION \
              --limit 1 \
              --json url \
              --jq .[].url)" >> $GITHUB_ENV

      - name: Instructions
        if: env.RUN == 'true'
        run: |
          cat << 'EOF'

          Next steps:

          1. Review the automated changes made on this branch.
             You can see the diff here:
             https://github.com/natcap/invest/compare/main...$AUTORELEASE_BRANCH
             If anything is incorrect, run the release rollback workflow,
             fix the issues on main, and then initiate the release again.

          2. Wait for the Github Actions checks on the tag to finish.
             Follow their status here: $TAG_RUN_URL
             If the checks fail due to an actual problem, run the release
             rollback workflow, fix the issues on main, and then initiate
             the release again.
             If the checks fail due to an intermittent issue, re-run the
             checks until they pass.

          3. Initiate the release part 2 workflow:
             https://github.com/natcap/invest/actions/workflows/release-part-2.yml

          EOF
